# Generated by Django 6.0.1 on 2026-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='my awesome blog', max_length=255),
        ),
    ]
