# Generated by Django 6.0.1 on 2026-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='software engineering', max_length=255),
        ),
    ]
